spring:
  profiles:
    active: dev

   #jpa设置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 驱动配置信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tododb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    #jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    #type: com.alibaba.druid.pool.DruidDataSource

    # 连接池的配置信息
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

  # redis数据库（默认为0）
  redis:
    database: 6
    # Redis服务器地址
    host: 192.168.0.216
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password:
#     pool:
    # 连接池最大连接数（使用负值表示没有限制）
#       max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#       max-wait: -1
    # 连接池中的最大空闲连接
#       max-idle: 8
    # 连接池中的最小空闲连接
#       min-idle: 0
    # 连接超时时间（毫秒）
    #timeout: 0
